max_width = 120
newline_style = "unix"
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
fn_params_layout = "Compressed"
single_line_if_else_max_width = 120
single_line_let_else_max_width = 120
use_small_heuristics = "Max"
